name: Sync README
on:
  push:
    paths:
    - 'README.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create outputs
      run: |
        echo "##[set-output name=slug;]${GITHUB_REPOSITORY//docker-/}"
        echo "##[set-output name=description;]$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}" | jq -r '.description')"
      id: create_outputs
    - name: Sync README
      uses: meeDamian/sync-readme@v1.0.5
      with:
        pass: ${{ secrets.DOCKER_PASS }}
        description: ${{ steps.create_outputs.outputs.description }}
        slug: ${{ steps.create_outputs.outputs.slug }}
