name: Version check
on:
  schedule:
    - cron:  '15,45 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [release]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Update files
      run: |
        bash update.sh
      id: update_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
    - name: Commit and push changes
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4.7.1
      with:
        commit_message: ${{ format('Updated to version - {0}', steps.update_files.outputs.version) }}
        branch: ${{ matrix.branch }}
    - name: Send discord notification
      if: "contains(steps.commit.outputs.changes_detected, 'true')"
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        VERSION: ${{ steps.update_files.outputs.version }}
        TAG: ${{ matrix.branch }}
      run: |
        json='{"embeds": [{"title": "'${GITHUB_REPOSITORY//docker-/}'","description": "Updated version `'${VERSION}'` detected for tag `'${TAG}'`.","color": 4886754,"footer": {"text": "Powered by GitHub Actions"},"timestamp": "'$(date -u --iso-8601=seconds)'"}]}'
        curl -fsSL -X POST -H "Content-Type: application/json" -d "${json}" "${DISCORD_WEBHOOK}"
