name: Upstream packages check
on:
  schedule:
    - cron:  '5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable]
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ matrix.branch }}
    - name: Check for updated packages
      run: |
        bash update.sh checkpackages
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Upstream packages have been updated
        branch: ${{ matrix.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
