name: Weekly build
on:
  schedule:
    - cron:  '0 22 * * 5'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable]
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ matrix.branch }}
    - name: Update files
      run: |
        stamp=$(date)
        echo "${stamp}" > .weekly-build
        echo "##[set-output name=stamp;]${stamp}"
      id: update_files
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: ${{ format('Weekly build - {0}', steps.update_files.outputs.stamp) }}
        branch: ${{ matrix.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
